### ISSUE TITLE
Pseudo transient methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SteadyStateDiffEq.jl#15]
- https://www.math.uci.edu/~qnie/Publications/ja62.pdf
- https://pdfs.semanticscholar.org/5706/1a163326620d425435d98e51fbe0aa14f1cc.pdf

**Comment by utkarsh530** [comment]
I went through this paper https://www.math.uci.edu/~qnie/Publications/ja62.pdf. I talk about solving ODEs at steady state using adaptive implicit Euler with inexact solver (AIIE) method. I cannot access the second link pdf. I have some questions regarding SteadyStateDiffEq.jl:
1. Do we currently have support for Laplacian operator, i.e. the diffusion term?
2. What exactly I have to implement in this issue? My initial guess is Something on the lines of RootFind algorithm using AIIE Method?
However, I found the alternative link https://ctk.math.ncsu.edu/PAPERS/Kelley_Liao_2013.pdf (I guess its the same paper). 

After reading both of them, I am pretty sure that we have to implement this scheme:

![image](https://user-images.githubusercontent.com/37050056/103804400-11cedf80-5078-11eb-98ad-909df2d24093.png)

For solving this ODE for the steady-state:

![image](https://user-images.githubusercontent.com/37050056/103805651-e3ea9a80-5079-11eb-859e-bc07666eb437.png)


My initial thoughts are that since this scheme is suited better for steady-state solutions but has a significant overlap with Newton's method, what could be the possible way to implement it? 

Instead of reinventing the whole wheel, it would be better to use the abstractions already written in `NLsolve.jl` (iteration scheme). Still, I am wondering how to handle the adaptive delta change. I guess that could be done by providing an "augmented Jacobian" to the NLsolve (The term `inv(delta)*I + F'(u)`) where F'(u) is the normal Jacobian. That would require separately handling NLsolve for SteadyStateDiffEqProblem because delta changes with each iteration and hence augmented Jacobian cannot be computed in normal ways. If we can handle calculating augmented Jacobian ourself for each iteration in SteadyState repo only, I guess that could work without writing code in NLsolve, which I am currently unaware of.

I could think of the naive way that working on the similar lines of `NLsolve.jl`, implement the code as a whole in the SteadyStateDiffEq.jl repository.  This could prove too strenuous and might be reinventing the whole wheel.

@ChrisRackauckas let me know your thoughts and help me design a suitable roadmap.

**Comment by utkarsh530** [comment]
Some step-sizing control strategies:
![image](https://user-images.githubusercontent.com/37050056/103807434-61170f00-507c-11eb-9f9a-5b60d51eba0c.png)
Source: https://www.csm.ornl.gov/seminars/images/ptc_ornl.pdf

**Comment by ChrisRackauckas** [comment]
https://projects.ncsu.edu/crsc//reports/ftp/pdf/crsc-tr02-18.pdf

**Comment by ChrisRackauckas** [comment]
https://epubs.siam.org/doi/abs/10.1137/S0036142903431298?journalCode=sjnaam
